# Quantum-Blue: Removed the ability for pierce damage to sever limbs, and raised
# thresholds for all limbs to 100 slash and 150 blunt
- type: entity
  abstract: true
  id: BaseHeadDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Slash: 100
    - types:
        Blunt: 150

- type: entity
  abstract: true
  id: BaseArmDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Slash: 100
    - types:
        Blunt: 150

- type: entity
  abstract: true
  id: BaseHandDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Slash: 100
    - types:
        Blunt: 150

- type: entity
  abstract: true
  id: BaseLegDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Slash: 100
    - types:
        Blunt: 150

- type: entity
  abstract: true
  id: BaseFootDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Slash: 100
    - types:
        Blunt: 150
